language: go
sudo: required
go:
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - 1.10
  - 1.11
before_install:
  - go get github.com/mattn/goveralls
install:
  - go get -d -t ./...
script:
  - go test ./...
  - $HOME/gopath/bin/goveralls -service=travis-ci
